# This is a basic workflow to help you get started with Actions

name: hello js action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: hello
        uses: v-stache/hello-world-javascript-action@master
        with:
          who-to-greet: "xingyu"
      - name: get output
        run: echo "The time was ${{steps.hello.outputs.time}}"
